services:
  olympics:
    image: postgres:17
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: olympics
      POSTGRES_PASSWORD: olympics
      POSTGRES_DB: olympics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U olympics -d olympics"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      olympics:
        condition: service_healthy
    command:
      [
        "-path", "/migrations/",
        "-database", "postgres://olympics:olympics@olympics:5432/olympics?sslmode=disable",
        "up"
      ]
    restart: "no"

  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      olympics:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      DB_URL: postgresql+psycopg2://olympics:olympics@olympics:5432/olympics
    command: ["python", "-u", "main.py"]

volumes:
  pgdata:
